### ISSUE TITLE
New issue "Depends: libgd3 (>= 2.1.1)"

### ISSUE THREAD

**Issue by michaelpporter** [geerlingguy/ansible-role-php-versions#15] opened 2018-02-05 13:41 UTC
PHP5.6 was working last night, this morning it is falling.

```bash
failed: [42.42.42.42] (item=[u'php5.6', u'php5.6-apcu', u'php5.6-cli', u'php5.6-common', u'php5.6-curl', u'php5.6-dev', u'php5.6-fpm', u'php5.6-gd', u'php5.6-imap', u'php5.6-json', u'php5.6-mbstring', u'php5.6-mcrypt', u'php5.6-opcache', u'php5.6-sqlite3', u'php5.6-xml', u'php5.6-yaml']) => {"cache_update_time": 1517836912, "cache_updated": false, "changed": false, "item": ["php5.6", "php5.6-apcu", "php5.6-cli", "php5.6-common", "php5.6-curl", "php5.6-dev", "php5.6-fpm", "php5.6-gd", "php5.6-imap", "php5.6-json", "php5.6-mbstring", "php5.6-mcrypt", "php5.6-opcache", "php5.6-sqlite3", "php5.6-xml", "php5.6-yaml"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     
install 'php5.6' 'php5.6-apcu' 'php5.6-cli' 'php5.6-common' 'php5.6-curl' 'php5.6-dev' 'php5.6-fpm' 'php5.6-gd' 'php5.6-imap' 'php5.6-json' 'php5.6-mbstring' 'php5.6-mcrypt' 'php5.6-opcache' 'php5.6-sqlite3' 'php5.6-xml' 'php5.6-yaml' -o APT::Install-Recommends=no' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n php5.6-gd : Depends: libgd3 (>= 2.1.1) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " php5.6-gd : Depends: libgd3 (>= 2.1.1) but it is not going to be installed"]}
```

Trying to install manually it seems something else was not updated.

```bash
sudo apt-get install libgd3
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd3 : Depends: libwebp5 (>= 0.4.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by michaelpporter** [comment] 2018-02-05 13:47
PS this is on Ubuntu 14.04

**Comment by geerlingguy** [comment] 2018-04-02 21:20
I just noticed this role doesn't have daily or weekly cron CI tests enabled, so I just enabled that to see what Travis CI says: https://travis-ci.org/geerlingguy/ansible-role-php-versions/builds/361367737

Note that Ubuntu 14.04 is used widely in Drupal VM, and often with PHP 5.6, and I haven't noticed anyone else reporting this issue. If this is on a VM or something, can you wipe it and start from scratch on a fresh build?

**Comment by geerlingguy** [comment] 2018-04-02 21:28
Seems like it worked on https://travis-ci.org/geerlingguy/ansible-role-php-versions/jobs/361367748 :/

Maybe it was an error with one version of 14.04's PHP GD package and it's working now?

See:

  - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843386

I'm going to close this as I can't reproduce it, but please let me know if you can find a way to reproduce this on a fresh build.

**Closed by geerlingguy** 2018-04-02 21:28 UTC
